// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Broadcast struct {
	ID       int32 `json:"id"`
	PostID   int32 `json:"post_id"`
	StatusID int32 `json:"status_id"`
}

type BroadcastChannel struct {
	ID          int32            `json:"id"`
	PostID      int32            `json:"post_id"`
	ChannelID   int32            `json:"channel_id"`
	PublishTime pgtype.Timestamp `json:"publish_time"`
	ExpireTime  pgtype.Timestamp `json:"expire_time"`
}

type BroadcastRecipient struct {
	ID          int32            `json:"id"`
	BroadcastID int32            `json:"broadcast_id"`
	UserID      int32            `json:"user_id"`
	SentAt      pgtype.Timestamp `json:"sent_at"`
}

type BroadcastStatus struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Channel struct {
	ID          int32            `json:"id"`
	ChatID      int64            `json:"chat_id"`
	ChannelName string           `json:"channel_name"`
	IsAdmin     pgtype.Bool      `json:"is_admin"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Post struct {
	ID        int32            `json:"id"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	ImageUrl  pgtype.Text      `json:"image_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID           int32            `json:"id"`
	ChatID       int64            `json:"chat_id"`
	Username     pgtype.Text      `json:"username"`
	FirstName    pgtype.Text      `json:"first_name"`
	LastName     pgtype.Text      `json:"last_name"`
	RoleID       int32            `json:"role_id"`
	IsSubscribed pgtype.Bool      `json:"is_subscribed"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
