version: "3"

services:
  apigateway:
    build: .
    depends_on:
      - otel-collector
      - zipkin
    ports:
      - "8080:8080"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
      - "8888:8888"
