apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: logservice
  name: logservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: logservice
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: KAFKA_BROKERS
              value: kafka:9092
            - name: SERVICE_NAME
              value: log-service
          image: mashukivan/telegrammanager-logservice
          name: logservice
      restartPolicy: Always
