apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: userservice
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: userservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: userservice
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: telegrammanager-postgres
            - name: DB_NAME
              value: telegrammanager
            - name: DB_PASSWORD
              value: mypassword
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: KAFKA_BROKERS
              value: kafka:9092
          image: mashukivan/telegrammanager-userservice
          name: userservice
          ports:
            - containerPort: 7077
              protocol: TCP
      restartPolicy: Always
