// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Broadcast struct {
	ID       int32 `json:"id"`
	PostID   int32 `json:"post_id"`
	StatusID int32 `json:"status_id"`
}

type BroadcastChannel struct {
	ID          int32     `json:"id"`
	PostID      int32     `json:"post_id"`
	ChannelID   int32     `json:"channel_id"`
	PublishTime time.Time `json:"publish_time"`
	ExpireTime  time.Time `json:"expire_time"`
}

type BroadcastRecipient struct {
	ID          int32        `json:"id"`
	BroadcastID int32        `json:"broadcast_id"`
	UserID      int32        `json:"user_id"`
	SentAt      sql.NullTime `json:"sent_at"`
}

type BroadcastStatus struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Channel struct {
	ID          int32        `json:"id"`
	ChatID      int64        `json:"chat_id"`
	ChannelName string       `json:"channel_name"`
	IsAdmin     sql.NullBool `json:"is_admin"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Post struct {
	ID        int32          `json:"id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	ImageUrl  sql.NullString `json:"image_url"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID           int32          `json:"id"`
	ChatID       int64          `json:"chat_id"`
	Username     sql.NullString `json:"username"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	RoleID       int32          `json:"role_id"`
	IsSubscribed sql.NullBool   `json:"is_subscribed"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
