name: ci-test

on:
  push: 
    branches: ['main', 'dev']

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Go 
      uses: actions/setup-go@v2
      with:
        go-version: ^1.22
      id: go
    
    - name: Checkout code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v .