name: ci-test

on:
  push:
    branches: ["main", "dev"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: telegrammanager
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mypassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6543:5432

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22
        id: go

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Install golang-migrate
        run: |
          git clone https://github.com/golang-migrate/migrate.git
          cd migrate
          go build -o migrate ./cmd/migrate
          sudo mv migrate /usr/bin/migrate

      - name: Run migrations
        run: sudo make migrateup

      - name: Test
        run: make test
